repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0  # use latest stable
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0  # use latest stable
    hooks:
      - id: flake8

  - repo: local
    hooks:
      - id: pytest
        name: run tests
        entry: pytest
        language: system
        pass_filenames: false
